package com.ops.entities;
// Generated 7 Dec, 2016 12:28:39 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FlatDetails generated by hbm2java
 */
@Entity
@Table(name = "FlatDetails", catalog = "PROJECT")
public class FlatDetails implements java.io.Serializable {

	private int PId;
	private PropertyDetails propertyDetails;
	private Integer flRooms;
	private Integer flBedrooms;
	private Integer flBalconies;
	private Boolean flCarPark;
	private Integer flLift;
	private String flFurnishState;

	public FlatDetails() {
	}

	public FlatDetails(PropertyDetails propertyDetails) {
		this.propertyDetails = propertyDetails;
	}
	
	public FlatDetails(int PId, int flRooms, int flBedrooms, int flBalconies, Boolean flCarPark,
			int flLift, String flFurnishState) {
		this.PId = PId;
		this.flRooms = flRooms;
		this.flBedrooms = flBedrooms;
		this.flBalconies = flBalconies;
		this.flCarPark = flCarPark;
		this.flLift = flLift;
		this.flFurnishState = flFurnishState;
	}

	public FlatDetails(PropertyDetails propertyDetails, Integer flRooms, Integer flBedrooms, Integer flBalconies,
			Boolean flCarPark, Integer flLift, String flFurnishState) {
		this.propertyDetails = propertyDetails;
		this.flRooms = flRooms;
		this.flBedrooms = flBedrooms;
		this.flBalconies = flBalconies;
		this.flCarPark = flCarPark;
		this.flLift = flLift;
		this.flFurnishState = flFurnishState;
	}

	//@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "propertyDetails"))
	@Id
	//@GeneratedValue(generator = "generator")

	@Column(name = "P_ID"/*, unique = true, nullable = false*/)
	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public PropertyDetails getPropertyDetails() {
		return this.propertyDetails;
	}

	public void setPropertyDetails(PropertyDetails propertyDetails) {
		this.propertyDetails = propertyDetails;
	}

	@Column(name = "FL_ROOMS")
	public Integer getFlRooms() {
		return this.flRooms;
	}

	public void setFlRooms(Integer flRooms) {
		this.flRooms = flRooms;
	}

	@Column(name = "FL_BEDROOMS")
	public Integer getFlBedrooms() {
		return this.flBedrooms;
	}

	public void setFlBedrooms(Integer flBedrooms) {
		this.flBedrooms = flBedrooms;
	}

	@Column(name = "FL_BALCONIES")
	public Integer getFlBalconies() {
		return this.flBalconies;
	}

	public void setFlBalconies(Integer flBalconies) {
		this.flBalconies = flBalconies;
	}

	@Column(name = "FL_CAR_PARK")
	public Boolean getFlCarPark() {
		return this.flCarPark;
	}

	public void setFlCarPark(Boolean flCarPark) {
		this.flCarPark = flCarPark;
	}

	@Column(name = "FL_LIFT")
	public Integer getFlLift() {
		return this.flLift;
	}

	public void setFlLift(Integer flLift) {
		this.flLift = flLift;
	}

	@Column(name = "FL_FURNISH_STATE", length = 30)
	public String getFlFurnishState() {
		return this.flFurnishState;
	}

	public void setFlFurnishState(String flFurnishState) {
		this.flFurnishState = flFurnishState;
	}

	@Override
	public String toString() 
	{
		return String.format(
				"FlatDetails [PId=%s, propertyDetails=%s, flRooms=%s, flBedrooms=%s, flBalconies=%s, flCarPark=%s, flLift=%s, flFurnishState=%s]",
				PId, propertyDetails, flRooms, flBedrooms, flBalconies, flCarPark, flLift, flFurnishState);
	}

	

}
