package com.ops.entities;
// Generated 7 Dec, 2016 12:28:39 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InterestedPropertyDetails generated by hbm2java
 */
@Entity
@Table(name = "InterestedPropertyDetails", catalog = "PROJECT")
public class InterestedPropertyDetails implements java.io.Serializable {

	private int ipId;
	private CustomerDetails customerDetails;
	private PropertyDetails propertyDetails;

	public InterestedPropertyDetails() {
	}

	public InterestedPropertyDetails(int ipId, CustomerDetails customerDetails, PropertyDetails propertyDetails) {
		this.ipId = ipId;
		this.customerDetails = customerDetails;
		this.propertyDetails = propertyDetails;
	}

	@Id

	@Column(name = "IP_ID", unique = true, nullable = false)
	public int getIpId() {
		return this.ipId;
	}

	public void setIpId(int ipId) {
		this.ipId = ipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_ID", nullable = false)
	public CustomerDetails getCustomerDetails() {
		return this.customerDetails;
	}

	public void setCustomerDetails(CustomerDetails customerDetails) {
		this.customerDetails = customerDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "P_ID", nullable = false)
	public PropertyDetails getPropertyDetails() {
		return this.propertyDetails;
	}

	public void setPropertyDetails(PropertyDetails propertyDetails) {
		this.propertyDetails = propertyDetails;
	}

}
