package com.ops.entities;
// Generated 7 Dec, 2016 12:28:39 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PinCityDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PinCityDetails", catalog = "PROJECT")
public class PinCityDetails implements java.io.Serializable {

	private int pin;
	private String division;
	private String city;
	private String district;
	private String state;
	private Set<CustomerDetails> customerDetailses = new HashSet<CustomerDetails>(0);
	private Set<PropertyDetails> propertyDetailses = new HashSet<PropertyDetails>(0);

	public PinCityDetails() {
	}

	public PinCityDetails(int pin, String division, String city, String district, String state) {
		this.pin = pin;
		this.division = division;
		this.city = city;
		this.district = district;
		this.state = state;
	}

	public PinCityDetails(int pin, String division, String city, String district, String state,
			Set<CustomerDetails> customerDetailses, Set<PropertyDetails> propertyDetailses) {
		this.pin = pin;
		this.division = division;
		this.city = city;
		this.district = district;
		this.state = state;
		this.customerDetailses = customerDetailses;
		this.propertyDetailses = propertyDetailses;
	}

	@Id
	@Column(name = "PIN", unique = true, nullable = false)
	public int getPin() {
		return this.pin;
	}

	public void setPin(int pin) {
		this.pin = pin;
	}

	@Column(name = "DIVISION", /*nullable = false,*/ length = 50)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "CITY", /*nullable = false,*/ length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "DISTRICT", /*nullable = false,*/ length = 20)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "STATE", /*nullable = false,*/ length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "pinCityDetails")
	public Set<CustomerDetails> getCustomerDetailses() {
		return this.customerDetailses;
	}

	public void setCustomerDetailses(Set<CustomerDetails> customerDetailses) {
		this.customerDetailses = customerDetailses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "pinCityDetails")
	public Set<PropertyDetails> getPropertyDetailses() {
		return this.propertyDetailses;
	}

	public void setPropertyDetailses(Set<PropertyDetails> propertyDetailses) {
		this.propertyDetailses = propertyDetailses;
	}

}
