package com.ops.entities;
// Generated 7 Dec, 2016 12:28:39 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResidentialPlotDetails generated by hbm2java
 */
@Entity
@Table(name = "ResidentialPlotDetails", catalog = "PROJECT")
public class ResidentialPlotDetails implements java.io.Serializable {

	private Integer rpId;
	private PropertyDetails propertyDetails;
	private double rpCarpetarea;
	private int rpFloors;
	private int rpRooms;
	private String rpFurnishState;

	public ResidentialPlotDetails() {
	}

	public ResidentialPlotDetails(PropertyDetails propertyDetails, double rpCarpetarea, int rpFloors, int rpRooms,
			String rpFurnishState) {
		this.propertyDetails = propertyDetails;
		this.rpCarpetarea = rpCarpetarea;
		this.rpFloors = rpFloors;
		this.rpRooms = rpRooms;
		this.rpFurnishState = rpFurnishState;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RP_ID", unique = true, nullable = false)
	public Integer getRpId() {
		return this.rpId;
	}

	public void setRpId(Integer rpId) {
		this.rpId = rpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "P_ID", nullable = false)
	public PropertyDetails getPropertyDetails() {
		return this.propertyDetails;
	}

	public void setPropertyDetails(PropertyDetails propertyDetails) {
		this.propertyDetails = propertyDetails;
	}

	@Column(name = "RP_CARPETAREA", nullable = false, precision = 22, scale = 0)
	public double getRpCarpetarea() {
		return this.rpCarpetarea;
	}

	public void setRpCarpetarea(double rpCarpetarea) {
		this.rpCarpetarea = rpCarpetarea;
	}

	@Column(name = "RP_FLOORS", nullable = false)
	public int getRpFloors() {
		return this.rpFloors;
	}

	public void setRpFloors(int rpFloors) {
		this.rpFloors = rpFloors;
	}

	@Column(name = "RP_ROOMS", nullable = false)
	public int getRpRooms() {
		return this.rpRooms;
	}

	public void setRpRooms(int rpRooms) {
		this.rpRooms = rpRooms;
	}

	@Column(name = "RP_FURNISH_STATE", nullable = false, length = 30)
	public String getRpFurnishState() {
		return this.rpFurnishState;
	}

	public void setRpFurnishState(String rpFurnishState) {
		this.rpFurnishState = rpFurnishState;
	}

}
