package com.ops.entities;
// Generated 7 Dec, 2016 12:28:39 AM by HibernateTools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShopDetails generated by hbm2java
 */
@Entity
@Table(name = "ShopDetails", catalog = "PROJECT")
public class ShopDetails implements java.io.Serializable {

	private Integer shId;
	private PropertyDetails propertyDetails;
	private boolean shCustomerParking;
	private String shFurnishState;

	public ShopDetails() {
	}

	public ShopDetails(PropertyDetails propertyDetails, boolean shCustomerParking, String shFurnishState) {
		this.propertyDetails = propertyDetails;
		this.shCustomerParking = shCustomerParking;
		this.shFurnishState = shFurnishState;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SH_ID", unique = true, nullable = false)
	public Integer getShId() {
		return this.shId;
	}

	public void setShId(Integer shId) {
		this.shId = shId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "P_ID", nullable = false)
	public PropertyDetails getPropertyDetails() {
		return this.propertyDetails;
	}

	public void setPropertyDetails(PropertyDetails propertyDetails) {
		this.propertyDetails = propertyDetails;
	}

	@Column(name = "SH_CUSTOMER_PARKING", nullable = false)
	public boolean isShCustomerParking() {
		return this.shCustomerParking;
	}

	public void setShCustomerParking(boolean shCustomerParking) {
		this.shCustomerParking = shCustomerParking;
	}

	@Column(name = "SH_FURNISH_STATE", nullable = false, length = 30)
	public String getShFurnishState() {
		return this.shFurnishState;
	}

	public void setShFurnishState(String shFurnishState) {
		this.shFurnishState = shFurnishState;
	}

}
